AWSTemplateFormatVersion: 2010-09-09
Description: >-
  property-assessment-helper
Transform:
- AWS::Serverless-2016-10-31

Resources:
  NotionAdapter:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: property-assessment-helper-notion-adapter
      Description: A Lambda function that logs the payload of messages sent to an
        associated SQS queue.
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      CodeUri: ../notion-adapter/
      Handler: src/app.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
      MemorySize: 128
      Timeout: 100
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - src/app.ts
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
